myjdbc:
  url: jdbc:mysql://localhost:3306/test
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: 123456
server:
  port: 4545
mybatis:
  typeAliasesPackage: com.demo
  mapperLocations: classpath:/sqlmapper/*.xml
  configLocation: classpath:/mybatis-config.xml